INSERT INTO `cms_labels` (`identifier`, `lang_code`, `label`) VALUES
('conf_find_change', 'en', 'You are about to change the values in <strong>[V][total]</strong> Objects. Proceed?'),
('conf_merge', 'en', 'You are about to merge <strong>[V][total]</strong> Objects. Proceed?'),
('conf_model_types_mode_not_share', 'en', '<p>All Types listed will remove the modes <strong>[V][type_mode]</strong>.</p>\r\n<p>Are you sure you wish to continue?</p>'),
('conf_model_types_mode_share', 'en', '<p>All Types listed will add the mode <strong>[V][type_mode]</strong>.</p>\r\n<p>Are you sure you wish to continue?</p>'),
('conf_object_delete', 'en', 'The Object will be deleted, are you sure?'),
('conf_object_find_change', 'en', '<p>You are about to change values in the following Objects.</p>\r\n\r\n<p>This functionality allows you to replace, append (for text, multi-value references, and non-single Sub-Objects), and remove Object Definitions and Sub-Objects.</p>\r\n\r\n<p>This functionality is heavily dependent on the active filter for text, multi-value references, and non-single Sub-Objects: by default the filtering criteria determine the values that can be changed.\r\nYou can override this behaviour and target the full Object Definition or all Sub-Objects of the same kind by disabling filtering.</p>'),
('conf_object_merge', 'en', '<p>You are about to merge the following Objects.</p>\r\n<p>With no Object selected in the list, a new Object will be created and the Objects will be merged sorted by their last update. When you select an Object in the list, the Objects will be merged towards the selected Object with the selected Object taking precedent.</p>\r\n\r\n<p>The merged Object will retain all cross-referenced Objects. The Objects used as source will be tagged as \'deleted\'. You have the option to commit or discard these changes.</p>'),
('inf_add_to_previous', 'en', 'Add value to default or previously set value.'),
('inf_administrator_visible', 'en', 'Only visible to Administrators.'),
('inf_analysis_context', 'en', 'Include results from other Analyses in the Analysis column in overviews.'),
('inf_analysis_introduction', 'en', '<p>Use the Analysis functionality to perform graph measures and metrics on the active data selection.</p>\r\n<p>Consult the <a href=\"http://nodegoat.net/documentation.s/85/analysis\" target=\"_blank\">documentation [V][icon]</a> for more information.</p>'),
('inf_analysis_open', 'en', 'Open Analysis configuration.'),
('inf_analysis_store', 'en', 'Save Analysis configuration.'),
('inf_analysis_unweighted', 'en', 'All edges are equal.'),
('inf_analysis_weighted', 'en', 'Add additional weight (total edge length) between nodes based on duplicate edges.'),
('inf_analysis_weighted_closeness', 'en', 'Edges add to a shorter total edge length (lower weight).'),
('inf_analysis_weighted_distance', 'en', 'Edges add to a longer total edge length (higher weight).'),
('inf_api_nodegoat_identifier_url', 'en', '<p>The following option enables nodegoat ID translation: use an URL template to translate nodegoat IDs to a specific location.</p>\r\n<p>Since it is possible for certain IDs to match multiple Objects in multiple Types, only the Objects for the first sorted Type in the project are returned.</p>\r\n<p>The translation provides values for the following tags:\r\n<ul>\r\n<li>The [[type]] tag provides the Type ID the object belongs to.</li>\r\n<li>The [[object]] tag presents the numeric Object ID.</li>\r\n<li>Put [multi] tags around the relevant section with the [[type]] and/or [[object]] tag to multiply that section when the ID matches more than one Object. Optionally, provide a separator should multiplication be available (e.g. [multi=_]).</li>\r\n<li>The [[identifier]] tag presents the used identifier.</li>\r\n</ul>\r\n</p>\r\n<pre><code>[V][example]</code></pre>\r\n<p>Leave the translation URL blank to return the API-output for the matched Object(s).</p>'),
('inf_application_filter', 'en', 'Apply filter to this [V][application].'),
('inf_application_path', 'en', 'Apply a path (Filter & Scope) to this [V][application].'),
('inf_condition_label', 'en', 'Add a label to this condition (shown in legends)'),
('inf_condition_model_conditions_use_current', 'en', 'Use this Type\'s active Condition (does not apply when loading Scenarios and Contexts).'),
('inf_conditions_open', 'en', 'Open Conditions.'),
('inf_conditions_store', 'en', 'Save Conditions.'),
('inf_context_include_scenarios', 'en', 'Include the data (Filter, Scope, and Conditions) from other Scenarios in the visualisation.'),
('inf_context_open', 'en', 'Open Contexts.'),
('inf_context_store', 'en', 'Save Contexts.'),
('inf_data_ingest_pointer_data', 'en', 'Result value from the Linked Data query.'),
('inf_data_ingest_pointer_query', 'en', 'Variable in the Linked Data query.'),
('inf_date_end_infinite', 'en', 'Infinite / no ending date.'),
('inf_date_source', 'en', 'Use a specific source to be used for the date.'),
('inf_date_start_infinite', 'en', 'Infinite / no starting date.'),
('inf_export_settings_open', 'en', 'Open Export Settings.'),
('inf_export_settings_store', 'en', 'Save Export Settings.'),
('inf_external_resource_query', 'en', '<p>The following SPARQL query is an example query that demonstrates the use of various configuration variables:</p>\r\n<pre><code>[V][example]</code></pre>\r\n<ul>\r\n<li>[query=name] with at least one [variable] tag is mandatory and is used for initial/quick searches.</li>\r\n<li>Additional [query=[i]x[/i]] tags can be used to perform advanced filtering, everything in between is removed when not filtered on.</li>\r\n<li>Multiple [query=[i]x[/i]] tags can exist that share the same x.</li>\r\n<li>[variable=[i]y[/i]] can be used to label variables.</li>\r\n<li>[variable=[i]y[/i]:uri-identifier] is a typed variable that is able to map a full URI to the identifier based on the URI template (e.g. \'http://uri.host/1234/\' to \'1234\').</li>\r\n<li>Multiple [variable] or [variable=[i]y[/i]] tags can exist in a single [query] that optionally share the same y.</li>\r\n<li>For the API protocol, the inclusion of [[offset]] and [[limit]] or [[limit=[i]n[/i]]] tags is mandatory.</li>\r\n</ul>\r\n<p>When testing the query, all [query] and [variable] tags will be stripped, leaving the values in between.</p>'),
('inf_external_resource_script', 'en', 'Prepare a script in JavaScript, based on an input variable INPUT, and that assigns a value to a variable OUTPUT.\r\n\r\nINPUT and OUTPUT can be any value/array/object. When OUTPUT is an array/object it will also be possible to assign each key/property as a separate OUTPUT variable.\r\n\r\nThe script is run client-side in a separate worker/thread with subsequent calls for every new INPUT value.'),
('inf_external_resource_static', 'en', 'Static Link'),
('inf_filter_add_extra', 'en', 'Add an extra filter.'),
('inf_filter_clear', 'en', 'Clear filter.'),
('inf_filter_exclude', 'en', 'Set filter to exclude results.'),
('inf_filter_exclude_hard', 'en', 'Multi-value references and non-single Sub-Objects: exclude the whole Object on matched filtering.'),
('inf_filter_exclude_soft', 'en', 'Multi-value references and non-single Sub-Objects: exclude their values on matched filtering.'),
('inf_filter_object_and_sub_and', 'en', 'Reduce the Object and Sub-Object result set from the filters (<em>n</em>) on the left.'),
('inf_filter_object_and_sub_or', 'en', 'Reduce the Object result set from the filters (<em>n</em>) on the left. Expand the result set for Sub-Objects of the same kind.'),
('inf_filter_object_optional_sub_optional', 'en', 'Optionally expand selection in the Object and Sub-Object result set (<em>n</em>) on the left.'),
('inf_filter_object_or_sub_or', 'en', 'Expand the Object and Sub-Object result set to the filters (<em>n</em>) on the left.'),
('inf_filter_store', 'en', 'Save filter configuration.'),
('inf_filter_user_exclude', 'en', 'Set filter to exclude users.'),
('inf_find_change_disable_filtering', 'en', 'Text, multi-value references, and non-single Sub-Objects: always target the full Object Definition and all Sub-Objects of the same kind; do not apply filtering.'),
('inf_frame_open', 'en', 'Open Frames.'),
('inf_frame_store', 'en', 'Save Frames.'),
('inf_import_element_used_for_reference', 'en', 'Element that will be used to make a Reference. If left blank, Quicksearch Descriptions will be used.'),
('inf_import_file', 'en', 'CSV files can be exported from every spreadsheet application. Make sure you use UTF-8 encoding when exporting the CSV file. After you have uploaded one or more CSV files, you can create Import Templates to connect the column headings of a CSV file to your Data Model.'),
('inf_import_filter_object_sub_identifier', 'en', 'Optionally, select a column in your CSV file to identify and update existing Sub-Objects.'),
('inf_import_incompatible_source', 'en', 'Number of column headings and columns does not match. Review your CSV file.'),
('inf_import_inspect_rows', 'en', 'Inspect the first, middle, and last row to see whether all content has been assigned correctly. If this is the case, click Next to resolve any present relationships and store the data.'),
('inf_import_log_info', 'en', 'This is a log of the last run of this template. The data that has been added or updated can be found in the [url=/login/data]Data section of your environment[/url].\r\n\r\nThis log will be stored for [V][removal_interval] and will be deleted on <strong>[V][removal_date]</strong>. The data that has been added or updated will remain in your environment.'),
('inf_import_pointer', 'en', 'Column heading in the CSV file.'),
('inf_import_pointer_link_object', 'en', 'Use one or more columns of your CSV file to identify existing Objects in nodegoat. If you rely on IDs produced by nodegoat, you can use the \'nodegoat ID\' option and specify the column in your CSV file that contains the nodegoat ID. If you do not rely on a nodegoat ID, you can use the \'Filter\' option to specify the columns that contain data with which you are able to identify existing Objects.\r\n\r\nIdentified Objects will be updated with data that is provided in other columns of this CSV file. These columns can be mapped to your Data Model in the next form.'),
('inf_import_pointer_map', 'en', 'Connect the columns of your CSV file to Object Descriptions, Sub-Objects, or Sub-Object Descriptions in your Data Model.'),
('inf_import_sub_object_of_location_reference_type', 'en', 'Sub-Object of Location Reference Type.'),
('inf_import_template', 'en', 'An Import Template connects column headings of a CSV file to your Data Model. Once you have created an Import Template, you can run this so that data in each row of the CSV file is assigned to its designated location in the Data Model.'),
('inf_import_template_process_select_source', 'en', 'Use the selected CSV file or select a different CSV file with similar column headings. '),
('inf_import_type_of_target_element', 'en', 'Type of Target Element.'),
('inf_ingest_filter_value', 'en', 'Value to be used as filter.'),
('inf_ingest_incompatible_source', 'en', 'The template variables & values do not match the needed variables & values in the Linked Data resource. Review your Linked Data resource.'),
('inf_ingest_pointer_value_index', 'en', 'Specify whether this splitted value contains multiple usable values or select one target position.'),
('inf_ingest_pointer_value_split', 'en', 'Optional: Character to use as splitter.'),
('inf_ingest_query_value', 'en', 'Value to be used for the query.'),
('inf_ingest_target_element', 'en', 'Target Element in Data Model.'),
('inf_ingest_unmatched_results', 'en', 'The strings below have been found in your [V][source]. They either have no match, or multiple matches with Objects in this Type. Assign one of the provided matched Objects to a string, or find another Object by using the search option. If no Object matches a string, select the N/A option.\r\n\r\nOnce all unmatched strings have been assigned, click Next to continue.'),
('inf_linked_data_copy_response_value', 'en', 'Use/copy selected response value.'),
('inf_location_reference_lock', 'en', 'Lock this part of the location reference at Object level.'),
('inf_location_reference_only', 'en', 'Only use location references.'),
('inf_location_source', 'en', 'Use a specific source to be used for the location Object reference.'),
('inf_object_description_clearance_edit', 'en', 'Minimum clearance to <strong>add / edit</strong> a Definition of this Description.'),
('inf_object_description_clearance_view', 'en', 'Minimum clearance to <strong>view</strong> a Definition of this Description.'),
('inf_object_description_default_value', 'en', 'Enter a default Definition for this Description which will be presented when entering new Objects.'),
('inf_object_description_has_default_value', 'en', 'Provide a default Definition for this Description.'),
('inf_object_description_has_multi', 'en', 'Possibility for multiple Definitions for this Description.'),
('inf_object_description_in_name', 'en', 'Use Description for Object name.'),
('inf_object_description_in_overview', 'en', 'Show Description in overviews.'),
('inf_object_description_in_search', 'en', 'Use Description for quick search.'),
('inf_object_description_is_identifier', 'en', 'Use the Description for Object identification (used in API queries).'),
('inf_object_description_is_required', 'en', 'A Definition for this Description is required.'),
('inf_object_description_is_unique', 'en', 'Definitions for this Description are unique.'),
('inf_object_description_multi_separator', 'en', 'Set a specific separator value when multiple Definitions are shown for this Object Description. Leave empty to use the default value.'),
('inf_object_description_name_separator', 'en', 'Set a specific separator value when this Object Description can contain multiple Definitions and is used for the Object name. Leave empty to use the default value.'),
('inf_object_sub_details_clearance_edit', 'en', 'Minimum clearance to <strong>add / edit</strong> a Sub-Object of this instance.'),
('inf_object_sub_details_clearance_view', 'en', 'Minimum clearance to <strong>view</strong> a Sub-Object of this instance.'),
('inf_override_default_or_previous', 'en', 'Override default or previously set value.'),
('inf_path_collapse', 'en', 'Collapse (contract) all relations for Objects at this position in the path.'),
('inf_path_connection_temporal', 'en', 'Apply and pass temporality to this and all subsequent time-bound connections in the path.'),
('inf_path_connection_temporal_origin', 'en', 'Apply and pass temporality to all subsequent time-bound connections in the path.'),
('inf_path_filter', 'en', 'Apply path-aware filtering (when applicable) to the Objects at this position in the path.'),
('inf_path_object_only', 'en', 'Only select the Object; do not include any Sub-Objects, cross-references, or values.'),
('inf_pattern_pair_assign_no_object', 'en', 'Click to assign no Object to this string.'),
('inf_pattern_pair_assign_object', 'en', 'Click to assign Object to this string.'),
('inf_pattern_pair_ignore', 'en', 'Click to ignore connecting an Object to this string.'),
('inf_pattern_pair_store', 'en', 'Connect Object with this specific string as a Pattern Pair.'),
('inf_project_date_references', 'en', 'Types that can be used as references in a Sub-Object\'s date Chronology.'),
('inf_project_full_scope', 'en', 'Use cross-referenced Objects outside the scope of the project.'),
('inf_project_include_referenced_edit', 'en', 'Include this Description in Object <strong>edit mode</strong> for the cross-referenced editing of Objects.'),
('inf_project_include_referenced_view', 'en', 'Include this Description in Object <strong>view mode</strong> to see its cross-referenced Objects.'),
('inf_project_location_references', 'en', 'Types that can be used as references for a Sub-Object\'s location.'),
('inf_project_object_description_edit', 'en', 'Include / Exclude the Definition of this Description to be <strong>added / edited</strong> in this project.'),
('inf_project_object_description_information', 'en', 'Provide optional information when editing a Definition of this Description.'),
('inf_project_object_description_view', 'en', 'Include / Exclude the Definition of this Description to be <strong>viewed</strong> in this project.'),
('inf_project_object_sub_details_edit', 'en', 'Include / Exclude Sub-Objects of this instance to be <strong>added / edited</strong> in this project.'),
('inf_project_object_sub_details_information', 'en', 'Provide optional information when editing a Sub-Object of this instance.'),
('inf_project_object_sub_details_view', 'en', 'Include / Exclude Sub-Objects of this instance to be <strong>viewed</strong> in this project.'),
('inf_project_source_references', 'en', 'Types that can be used as source references for an Object.'),
('inf_project_type_color', 'en', 'Give this Type a color within the project.'),
('inf_project_type_condition', 'en', 'Apply Conditions to this Type.'),
('inf_project_type_context', 'en', 'Set a default Context for this Type.'),
('inf_project_type_edit', 'en', 'Allow an Object of this Type to be <strong>added / edited</strong> in this project.'),
('inf_project_type_filter', 'en', 'Use a filter to limit this Type.'),
('inf_project_type_filter_object_subs', 'en', 'Apply filtering to Sub-Objects.'),
('inf_project_type_frame', 'en', 'Set a default Frame for this Type.'),
('inf_project_type_in_user_interface_filter', 'en', 'Type is available as a filter only.'),
('inf_project_type_information', 'en', 'Provide optional information when editing an Object of this Type.'),
('inf_project_type_is_user_interface_filter', 'en', 'Type is available to be filtered (filteree) in user interface.'),
('inf_project_use_projects', 'en', 'Projects that are available to be sourced for Filters, Scopes, Contexts, Conditions, Analyses, Frames, Visual Settings & Scenarios'),
('inf_reconcile_match_difference', 'en', 'Maximum difference in score when multiple Object patterns match on the same text. Keep the highest scoring Object and other Objects this close to that score. Between 0 and 99.'),
('inf_reconcile_match_prioritise_pattern_pair', 'en', 'When multiple Object patterns match on the same text and these include Pattern Pairs, discard any matches that are not Pattern Pairs.'),
('inf_reconcile_match_results', 'en', 'The source values below have been found in their corresponding Objects. They either have no match, or multiple matches with Objects in the reconciliation / testing Type. Assign one of the provided matched Objects, or find another Object by using the search option. If no Object matches the source value, select the N/A option.\r\n\r\nOnce all Objects have been assigned, click Next to continue.'),
('inf_reconcile_overlap_difference', 'en', 'Maximum difference in score when multiple Object patterns overlap on the same text. Keep the highest scoring Object and other Objects this close to that score. Between 0 and 99.'),
('inf_reconcile_pattern_complete', 'en', 'Extend a matched value to the nearest whitespace or punctuation (i.e. whole word).'),
('inf_reconcile_pattern_distance', 'en', 'Maximum distance in characters between separate matched values by an Object\'s pattern.'),
('inf_reconcile_pattern_threshold', 'en', 'Set the sensitivity to match a value part of an Object\'s pattern. Between 0 and 100.<br />\r\n0 = Value matches anywhere.<br />\r\n100 = Value matches a word; value is surrounded by whitespace or punctuation.'),
('inf_reconcile_select_source_test', 'en', 'Select a source value and a reconciliation value to be able to store the resolved/reconciled reference.'),
('inf_reconcile_store_tags', 'en', 'Store found Objects as tags in the source text.'),
('inf_reconcile_test_pattern_pairs', 'en', 'Include and prioritise Pattern Pairs to reconcile Objects.'),
('inf_reconcile_threshold', 'en', 'Discard Object when the score is below a certain threshold. Between 1 and 100.'),
('inf_relationality_filter_no', 'en', 'Count all references from a matched Object.'),
('inf_relationality_filter_yes', 'en', 'Count only the references matched in the filter.'),
('inf_relationality_group_no', 'en', 'Count all cross-referenced (Sub-)Object references.'),
('inf_relationality_group_yes', 'en', 'Count cross-referenced Objects only once.'),
('inf_replace_text_value', 'en', 'Replace text with an other value.'),
('inf_scenario_cache_retain', 'en', 'Retain the cached version of the Scenario for as long as possible until it is manually invalidated.'),
('inf_scenario_disables_cache', 'en', 'Setting this option disables Scenario caching.'),
('inf_scenario_use_current_setting', 'en', 'Use this Type\'s active [V][setting].'),
('inf_scope_open', 'en', 'Open Scope selections.'),
('inf_scope_store', 'en', 'Save Scope selections.'),
('inf_select_source_file', 'en', 'Select a source file and starting position.'),
('inf_size_start', 'en', 'Lower bound for weighted data.'),
('inf_size_stop', 'en', 'Upper bound for weighted data.'),
('inf_type_clearance_edit', 'en', 'Minimum clearance to <strong>add / edit</strong> an Object of this Type.'),
('inf_type_color', 'en', 'Give this Type a default color.'),
('inf_type_conditions', 'en', 'Apply Conditions to this Type.'),
('inf_user_self', 'en', 'Use the identification of the engaging user (i.e. yourself).'),
('inf_visual_settings_capture', 'en', 'When enabled, visualisations will show an additional download button in the top-right corner to save the visualisation as a high-resolution image.\r\nOnly enable this feature when needed, since the capture settings will slow visualisations down!'),
('inf_visual_settings_open', 'en', 'Open Visual Settings.'),
('inf_visual_settings_store', 'en', 'Save Visual Settings.'),
('lbl_algorithm_force_charge', 'en', 'Node Gravity'),
('lbl_algorithm_force_friction', 'en', 'Network Friction'),
('lbl_algorithm_force_gravity', 'en', 'Center Gravity'),
('lbl_algorithm_force_theta', 'en', 'Network Approximation'),
('lbl_algorithm_forceatlas2_adjust_sizes', 'en', 'Node Weight'),
('lbl_algorithm_forceatlas2_edge_weight_influence', 'en', 'Edge Weight Influence'),
('lbl_algorithm_forceatlas2_gravity', 'en', 'Network Gravity'),
('lbl_algorithm_forceatlas2_lin_log_mode', 'en', 'Lin-Log Mode'),
('lbl_algorithm_forceatlas2_optimize', 'en', 'Network Approximation'),
('lbl_algorithm_forceatlas2_optimize_theta', 'en', 'Network Approximation'),
('lbl_algorithm_forceatlas2_outbound_attraction_distribution', 'en', 'Outbound Attraction'),
('lbl_algorithm_forceatlas2_scaling_ratio', 'en', 'Scaling'),
('lbl_algorithm_forceatlas2_slow_down', 'en', 'Slow Down'),
('lbl_algorithm_forceatlas2_strong_gravity_mode', 'en', 'Strong Network Gravity'),
('lbl_analyse_path', 'en', 'Analyse Path'),
('lbl_analysis_betweenness_centrality', 'en', 'Betweenness Centrality'),
('lbl_analysis_centrality', 'en', 'Centrality'),
('lbl_analysis_closeness_centrality', 'en', 'Closeness Centrality'),
('lbl_analysis_closeness_eccentricity', 'en', 'Closeness Eccentricity'),
('lbl_analysis_clustering_coefficient', 'en', 'Clustering Coefficient'),
('lbl_analysis_context', 'en', 'Analysis Context'),
('lbl_analysis_damping', 'en', 'Damping'),
('lbl_analysis_degree_centrality', 'en', 'Degree Centrality'),
('lbl_analysis_graph_dense', 'en', 'Dense'),
('lbl_analysis_graph_sparse', 'en', 'Sparse'),
('lbl_analysis_iterations', 'en', 'Iterations'),
('lbl_analysis_pagerank', 'en', 'Pagerank'),
('lbl_analysis_provide', 'en', 'Additional modes of analysis'),
('lbl_analysis_secondary_value', 'en', 'Secondary Value'),
('lbl_analysis_shortest_path', 'en', 'Shortest Path'),
('lbl_analysis_shortest_path_betweenness_centrality', 'en', 'Include a betweenness centrality of Objects that are within a shortest path. The measure will be added as a secondary value to the Object\'s path distance.'),
('lbl_analysis_unweighted', 'en', 'Unweighted'),
('lbl_analysis_weighted', 'en', 'Weighted'),
('lbl_analysis_weighted_closeness', 'en', 'Weight to Closeness'),
('lbl_analysis_weighted_distance', 'en', 'Weight to Distance'),
('lbl_analysis_weighted_max', 'en', 'Weight Max'),
('lbl_analysis_weighted_mode', 'en', 'Mode'),
('lbl_api_nodegoat_identifier_url', 'en', 'Translation URL'),
('lbl_append_to_similar', 'en', 'Append to similar'),
('lbl_arrowhead', 'en', 'Arrowhead'),
('lbl_backup_nodegoat', 'en', 'Backup nodegoat structure & data'),
('lbl_cache_objects', 'en', 'Object Cache'),
('lbl_category_descriptions', 'en', 'Category Descriptions'),
('lbl_category_self', 'en', 'This Category'),
('lbl_centrality_betweenness', 'en', 'Betweenness'),
('lbl_centrality_degree', 'en', 'Degree'),
('lbl_centrality_degree_per_type', 'en', 'Degree (per Type)'),
('lbl_centrality_indegree', 'en', 'Indegree'),
('lbl_centrality_outdegree', 'en', 'Outdegree'),
('lbl_centrality_pagerank', 'en', 'PageRank'),
('lbl_centrality_weighted', 'en', 'weighted'),
('lbl_chronology', 'en', 'Chronology'),
('lbl_cite_as', 'en', 'Cite as'),
('lbl_cleanup_objects', 'en', 'Cleanup Objects'),
('lbl_click_for_more_information_on', 'en', 'Click here for more information on'),
('lbl_collection', 'en', 'Collection'),
('lbl_color_background', 'en', 'Background Colour'),
('lbl_color_button', 'en', 'Button Colour'),
('lbl_color_header', 'en', 'Header Colour'),
('lbl_condition_model_conditions', 'en', 'Conditions in Data Model'),
('lbl_created', 'en', 'Created'),
('lbl_credentials_add', 'en', 'Add Credentials'),
('lbl_criteria', 'en', 'Criteria'),
('lbl_cumulative', 'en', 'Cumulative'),
('lbl_data_ingest_cache', 'en', 'External Resource Cache'),
('lbl_data_ingest_pointer_data', 'en', 'Result Value'),
('lbl_data_ingest_pointer_query', 'en', 'Query Variable'),
('lbl_data_ingest_source', 'en', 'External Resource'),
('lbl_date_cycle', 'en', 'Cycle'),
('lbl_date_period', 'en', 'Date Period'),
('lbl_date_point', 'en', 'Date Point'),
('lbl_date_statement', 'en', 'Date Statement'),
('lbl_date_type', 'en', 'Date Type'),
('lbl_definition', 'en', 'Definition'),
('lbl_definitions', 'en', 'Definitions'),
('lbl_descriptions', 'en', 'Descriptions'),
('lbl_disable_responsive_layout', 'en', 'Disable Responsive Layout'),
('lbl_disconnected', 'en', 'Disconnected'),
('lbl_discussion_objects', 'en', 'Object Discussion'),
('lbl_dot', 'en', 'Dot'),
('lbl_enter_search_terms', 'en', 'Enter search terms or select keywords to explore'),
('lbl_exit', 'en', 'Exit'),
('lbl_export_format', 'en', 'Export Format'),
('lbl_export_format_enclose', 'en', 'Enclose'),
('lbl_export_format_flow', 'en', 'Object Flow'),
('lbl_export_format_flow_break', 'en', 'Page Break'),
('lbl_export_format_flow_continuous', 'en', 'Continuous'),
('lbl_export_format_include_description_name', 'en', 'Include Descriptions'),
('lbl_export_format_seperator', 'en', 'Separator'),
('lbl_export_format_type', 'en', 'Format Type'),
('lbl_external', 'en', 'External'),
('lbl_filter_advanced_input', 'en', 'FilterJSON or Object ID List'),
('lbl_filter_exclude_hard', 'en', 'Hard Exclude'),
('lbl_filter_exclude_soft', 'en', 'Soft Exclude'),
('lbl_filter_notify', 'en', 'Filter Notifications'),
('lbl_filter_object_and_sub_and', 'en', 'Reduction Filter (Object & Sub-Object)'),
('lbl_filter_object_and_sub_or', 'en', 'Reduction Filter (Object)'),
('lbl_filter_object_optional_sub_optional', 'en', 'Optional Filter'),
('lbl_filter_object_or_sub_or', 'en', 'Addition Filter'),
('lbl_filtering_disable', 'en', 'Disable Filtering'),
('lbl_fixed_projection', 'en', 'Fixed Projection'),
('lbl_geo', 'en', 'Geographical'),
('lbl_geo_centre', 'en', 'Centre'),
('lbl_geo_info', 'en', 'Geometric Information'),
('lbl_geo_visualisation', 'en', 'Geographical Visualisation'),
('lbl_geometry', 'en', 'Geometry'),
('lbl_graph', 'en', 'Graph'),
('lbl_grid', 'en', 'Grid'),
('lbl_grid_overlay', 'en', 'Grid Overlay'),
('lbl_highlight_color', 'en', 'Highlight Colour'),
('lbl_hint', 'en', 'Hint'),
('lbl_image_header', 'en', 'Header Image'),
('lbl_import_cleanup_import_template_logs', 'en', 'Cleanup Import Template Logs'),
('lbl_import_ignore_empty', 'en', 'Ignore when Empty'),
('lbl_import_ignore_identical', 'en', 'Ignore when Identical'),
('lbl_import_limit', 'en', 'Import Limit'),
('lbl_import_log_ignored_empty', 'en', 'Ignored Empty Value'),
('lbl_import_log_ignored_identical', 'en', 'Ignored Identical Value'),
('lbl_import_log_no_object', 'en', 'Missing Object'),
('lbl_import_log_no_object_sub', 'en', 'Missing Sub-Object'),
('lbl_import_log_no_reference', 'en', 'Missing Reference'),
('lbl_import_log_open', 'en', 'Click here to view the log of this run.'),
('lbl_import_pointer', 'en', 'Column'),
('lbl_import_remove_column', 'en', 'Remove Column.'),
('lbl_import_row_number', 'en', 'Row Number'),
('lbl_import_source', 'en', 'CSV File'),
('lbl_import_specify_additional_options', 'en', 'Specify additional options.'),
('lbl_import_template', 'en', 'Import Template'),
('lbl_import_templates', 'en', 'Import Templates'),
('lbl_include_type', 'en', 'Include Type'),
('lbl_information_retrieval', 'en', 'Information Retrieval'),
('lbl_ingest_objects_add', 'en', 'Add New Objects'),
('lbl_ingest_objects_add_if_not_exists', 'en', 'Add New Objects (If Not Exists)'),
('lbl_ingest_objects_identify', 'en', 'Identify Objects By'),
('lbl_ingest_objects_update', 'en', 'Update Existing Objects'),
('lbl_ingest_show_log', 'en', 'Show Log'),
('lbl_ingest_template_link_object', 'en', 'Link [V][source] To Object'),
('lbl_ingest_template_link_type_object', 'en', 'Query [V][source] By Object Value'),
('lbl_ingest_template_map', 'en', 'Map [V][source] To Data Model'),
('lbl_ingest_template_query_filter_value', 'en', 'Query / Filter [V][source] By Value'),
('lbl_ingest_unmatched_results', 'en', 'Unmatched Results'),
('lbl_initial', 'en', 'Initial'),
('lbl_instance', 'en', 'Instance'),
('lbl_last_run', 'en', 'Last Run'),
('lbl_last_update', 'en', 'Last Update'),
('lbl_latitude', 'en', 'Latitude'),
('lbl_line', 'en', 'Line'),
('lbl_linked_data', 'en', 'Linked Data'),
('lbl_links_available', 'en', 'links available'),
('lbl_location_reference', 'en', 'Location Reference'),
('lbl_location_references', 'en', 'Location References'),
('lbl_location_type', 'en', 'Location Type'),
('lbl_location_value', 'en', 'Location Value'),
('lbl_longitude', 'en', 'Longitude'),
('lbl_marginalia', 'en', 'Marginalia'),
('lbl_mode', 'en', 'Mode'),
('lbl_mode_connect', 'en', 'Connection'),
('lbl_mode_move', 'en', 'Movement'),
('lbl_model_filter_label', 'en', 'Filter On Label'),
('lbl_model_filter_project', 'en', 'Filter On Project'),
('lbl_modify', 'en', 'Modify'),
('lbl_music_notation_clef', 'en', 'Clef'),
('lbl_music_notation_code', 'en', 'Code'),
('lbl_music_notation_key_signature', 'en', 'Key Signature'),
('lbl_music_notation_time_signature', 'en', 'Time Signature'),
('lbl_nodegoat_id', 'en', 'nodegoat ID'),
('lbl_object_description', 'en', 'Object Description'),
('lbl_object_description_value_type_music_notation', 'en', 'Music Notation'),
('lbl_object_descriptions', 'en', 'Object Descriptions'),
('lbl_object_id', 'en', 'Object ID'),
('lbl_object_name_in_overview', 'en', 'In Overviews'),
('lbl_object_only', 'en', 'Object Only'),
('lbl_object_self', 'en', 'This Object'),
('lbl_object_sub', 'en', 'Sub-Object'),
('lbl_object_sub_id', 'en', 'Sub-Object ID'),
('lbl_object_subs', 'en', 'Sub-Objects'),
('lbl_object_subs_unknown', 'en', 'Missing or Incomplete Sub-Objects'),
('lbl_odis_id', 'en', 'ODIS ID'),
('lbl_order_by', 'en', 'Order by'),
('lbl_overwrite', 'en', 'Overwrite'),
('lbl_pattern_composition', 'en', 'Composition'),
('lbl_pattern_composition_map', 'en', 'Mapped Value'),
('lbl_pattern_composition_match', 'en', 'Match Value'),
('lbl_pattern_composition_match_context', 'en', 'Match Value + Context'),
('lbl_pattern_context', 'en', 'Pattern Context'),
('lbl_pattern_pair', 'en', 'Pattern Pair'),
('lbl_pattern_pairs', 'en', 'Pattern Pairs'),
('lbl_pattern_text_boundary_character', 'en', 'Any Word Character'),
('lbl_pattern_text_boundary_void', 'en', 'White Space or Punctuation'),
('lbl_predefine_object_subs', 'en', 'Predefine Sub-Objects'),
('lbl_presentation', 'en', 'Presentation'),
('lbl_primary_project', 'en', 'Primary Project'),
('lbl_project_full_scope', 'en', 'Full Scope'),
('lbl_protocol', 'en', 'Protocol'),
('lbl_public_interface', 'en', 'Public Interface'),
('lbl_public_interface_amount_keywords', 'en', '[V][keywords_total] filter options.'),
('lbl_public_interface_amount_keywords_refine', 'en', '[V][keywords_amount] of [V][keywords_total] filter options. Type to refine.'),
('lbl_public_interface_and_or_statement', 'en', 'AND statement. Click to switch to OR statement'),
('lbl_public_interface_central_types', 'en', 'Central Types'),
('lbl_public_interface_cleanup_selections', 'en', 'Cleanup Public Interface Selections'),
('lbl_public_interface_colophon', 'en', 'Colophon'),
('lbl_public_interface_custom_labels', 'en', 'Custom Labels'),
('lbl_public_interface_dynamic_view_selection', 'en', 'Dynamic View Selection'),
('lbl_public_interface_exploration_types', 'en', 'Exploration Types'),
('lbl_public_interface_explore', 'en', 'Explore'),
('lbl_public_interface_explore_additional_data', 'en', 'Explore More Additional Data'),
('lbl_public_interface_explore_empty', 'en', 'Explore Empty'),
('lbl_public_interface_explore_more', 'en', 'Explore More'),
('lbl_public_interface_filter_types', 'en', 'Filter Types'),
('lbl_public_interface_license', 'en', 'License'),
('lbl_public_interface_media_types', 'en', 'Media Types'),
('lbl_public_interface_networks', 'en', 'Networks'),
('lbl_public_interface_networks_info', 'en', 'Networks Information'),
('lbl_public_interface_or_and_statement', 'en', 'OR statement. Click to switch to AND statement'),
('lbl_public_interface_random_objects', 'en', 'Random Objects'),
('lbl_public_interface_search_types', 'en', 'Search Types'),
('lbl_public_interface_use_combined_references_as_filters', 'en', 'Use Combined References as Filters'),
('lbl_queries', 'en', 'Queries'),
('lbl_query', 'en', 'Query'),
('lbl_query_url', 'en', 'Query URL'),
('lbl_quick_search', 'en', 'Quick Search'),
('lbl_radius_km', 'en', 'Radius (km)'),
('lbl_reconcile', 'en', 'Reconcile'),
('lbl_reconcile_batch_amount', 'en', 'Process Objects Batch'),
('lbl_reconcile_match_any', 'en', 'Any Result'),
('lbl_reconcile_match_certain', 'en', 'Fully Matched'),
('lbl_reconcile_match_difference', 'en', 'Multi-Match Score Difference'),
('lbl_reconcile_match_prioritise_pattern_pair', 'en', 'Multi-Match Prioritise Pattern Pairs'),
('lbl_reconcile_match_results', 'en', 'Match [V][count] Results'),
('lbl_reconcile_overlap_difference', 'en', 'Multi-Overlap Score Difference'),
('lbl_reconcile_pattern_complete', 'en', 'Extend Match'),
('lbl_reconcile_pattern_distance', 'en', 'Pattern Distance'),
('lbl_reconcile_pattern_threshold', 'en', 'Pattern Sensitivity'),
('lbl_reconcile_source', 'en', 'Source Value'),
('lbl_reconcile_store_auto', 'en', 'Auto-Save Results'),
('lbl_reconcile_store_tags_all', 'en', 'All Identical Matches'),
('lbl_reconcile_store_tags_first', 'en', 'First Match Only'),
('lbl_reconcile_target', 'en', 'Store Result'),
('lbl_reconcile_test', 'en', 'Reconcile / Test'),
('lbl_reconcile_threshold', 'en', 'Score Threshold'),
('lbl_reference', 'en', 'Reference'),
('lbl_relationality', 'en', 'Relationality (amount of references)'),
('lbl_relationality_filter_no', 'en', 'All'),
('lbl_relationality_filter_yes', 'en', 'Filter'),
('lbl_relationality_group_no', 'en', 'Soft'),
('lbl_relationality_group_yes', 'en', 'Hard'),
('lbl_relationality_object_subs', 'en', 'Subobject Count'),
('lbl_reversal', 'en', 'Reversal'),
('lbl_reversals', 'en', 'Reversals'),
('lbl_reversed_classification', 'en', 'Reversed Classification'),
('lbl_reversed_classification_reference', 'en', 'Classify With'),
('lbl_reversed_collection', 'en', 'Reversed Collection'),
('lbl_rows', 'en', 'Rows'),
('lbl_scope_advanced_input', 'en', 'ScopeJSON'),
('lbl_similar_object', 'en', 'Similar Object'),
('lbl_similar_objects', 'en', 'Similar Objects'),
('lbl_site_attribution', 'en', '<a href=\"http://nodegoat.net\" target=\"_blank\">nodegoat</a>'),
('lbl_soc', 'en', 'Social'),
('lbl_soc_visualisation', 'en', 'Social Visualisation'),
('lbl_social_options', 'en', 'Social Visualisation Options'),
('lbl_sort_limit', 'en', 'Sort Limit'),
('lbl_source_file', 'en', 'Source File'),
('lbl_source_files', 'en', 'Source Files'),
('lbl_source_referencing', 'en', 'Source Referencing'),
('lbl_static', 'en', 'Static'),
('lbl_static_layout', 'en', 'Force static layout'),
('lbl_steps', 'en', 'Steps'),
('lbl_stroke_color', 'en', 'Stroke Colour'),
('lbl_stroke_width', 'en', 'Stroke Width'),
('lbl_subtitle', 'en', 'Subtitle'),
('lbl_surface', 'en', 'Surface'),
('lbl_system_ingestion', 'en', 'Ingestion'),
('lbl_system_reconciliation', 'en', 'Reconciliation'),
('lbl_temporal', 'en', 'Temporal'),
('lbl_texts', 'en', 'Texts'),
('lbl_thumbnail', 'en', 'Thumbnail'),
('lbl_time', 'en', 'Chronological'),
('lbl_time_and_space', 'en', 'Time & Space'),
('lbl_time_visualisation', 'en', 'Chronological Visualisation'),
('lbl_trailblazer', 'en', 'Trailblazer'),
('lbl_type', 'en', 'Type'),
('lbl_type_module_objects_processed', 'en', 'Objects Processed'),
('lbl_type_unknown', 'en', 'Type UNKNOWN'),
('lbl_use_current_object_for_children', 'en', 'Use current object for children'),
('lbl_use_filtered_objects_as_children', 'en', 'Use filtered objects as descendants'),
('lbl_use_object_name', 'en', 'Fixed Field'),
('lbl_use_set_object', 'en', 'Use set object'),
('lbl_use_source_file_structure', 'en', 'Structure'),
('lbl_user_self', 'en', 'Myself'),
('lbl_versioning', 'en', 'Versioning'),
('lbl_viaf_number', 'en', 'VIAF Number'),
('lbl_view_limit', 'en', 'View Limit'),
('lbl_visual_hint', 'en', 'Visual Hint'),
('lbl_visual_settings', 'en', 'Visual Settings'),
('lbl_visualisation', 'en', 'Visualisation'),
('lbl_visualisations', 'en', 'Visualisations'),
('lbl_visualise', 'en', 'Visualise'),
('lbl_wikipedia_id', 'en', 'Wikipedia ID'),
('msg_analysis_no_configuration', 'en', 'No active Analysis found. First set-up an Analysis in order to run it.'),
('msg_analysis_no_graph', 'en', 'This function is not available. The server is currently not configured to host a graph database.'),
('msg_analysis_no_service', 'en', 'Analysis is currently not available for this algorithm, the required service is not running.'),
('msg_building_cache_object', 'en', 'Building Object cache...'),
('msg_building_cache_scenario_filter', 'en', 'Updating Scenario Filter cache...'),
('msg_building_cache_scenario_visualisation', 'en', 'Updating Scenario Visualisation cache...'),
('msg_condition_store_empty', 'en', 'The Conditions cannot be stored as there is nothing configured.'),
('msg_data_range_objects_found', 'en', 'A total of <strong>[V][count_objects]</strong> Objects and <strong>[V][count_object_subs]</strong> Sub-Objects from <strong>[V][type]</strong> have been selected.'),
('msg_export_not_available', 'en', 'There is nothing to export, please check your settings.'),
('msg_external_resource_error', 'en', '<strong>[V][resource_name]</strong> returned with an error. Please check your configuration and consult the external resource to see if there are additional guidelines.\r\n\r\nThe response from <strong>[V][resource_name]</strong> was:\r\n<div><code>[V][response]</code></div>\r\n<div class=\"hide-edit hide\"><div><div>URL:</div><code>[V][debug_url]</code></div></div><div>[+Debug URL]</div>\r\n<div class=\"hide-edit hide\"><div><div>Query:</div><code>[V][debug_query]</code></div></div><div>[+Debug Query]</div>'),
('msg_external_resource_error_parse', 'en', 'The response of <strong>[V][resource_name]</strong> cannot be read correctly, please make sure the output is valid JSON.'),
('msg_external_resource_error_parse_value', 'en', 'Error parsing [V][parse_name]'),
('msg_external_resource_running', 'en', 'Querying <strong>[V][resource_name]</strong>, please wait (will timeout automatically after <strong>[V][seconds] seconds</strong>).'),
('msg_external_resource_timeout', 'en', '<strong>[V][resource_name]</strong> timed out. Trying again to get at least a single result. '),
('msg_external_resource_timeout_found_records', 'en', 'Found [V][count] record(s) in <strong>[V][resource_name], trying to get more.'),
('msg_external_resource_timeout_stop', 'en', '<strong>[V][resource_name]</strong> timed out and did not return any results. The <strong>query might be too heavy</strong>, please check your settings.'),
('msg_filter_invalid', 'en', 'A filter that is part of this request is invalid or not found.'),
('msg_filter_notify', 'en', 'Your dataset has recently been updated. Click <a href=\"[V][link]\" target=\"_blank\">here</a> to review the latest changes.'),
('msg_filter_notify_title', 'en', 'Your dataset \'[V][name]\' has been updated.'),
('msg_filter_store_empty', 'en', 'The filter cannot be stored as the filter does not contain any valid information.'),
('msg_import_inspect_template_source', 'en', 'Inspect your Template and/or [V][source] to resolve this error.'),
('msg_import_limit_exceeded', 'en', 'This CSV file exceeds the limit of [V][limit] rows.'),
('msg_import_log_created', 'en', 'A log has been created of this import run.'),
('msg_import_no_files', 'en', 'There are currently no CSV files available. Go to the tab \'CSV Files\' to upload a CSV file.'),
('msg_ingest_done', 'en', 'All results have been processed and <strong>[V][count]</strong> Objects have been [V][verb]. Go to the [url=/login/data]Data section of your environment[/url] to inspect these Objects.'),
('msg_ingest_error_at_row_number', 'en', 'An error occurred while processing row number [V][row_number].'),
('msg_ingest_error_at_value', 'en', 'The error occurred while processing the value(s):'),
('msg_ingest_error_resolving_filters', 'en', 'An error occurred while resolving the filters of this Template:'),
('msg_ingest_filters_found', 'en', 'Found <strong>[V][count]</strong> Object filters.'),
('msg_ingest_locked', 'en', 'Object was open for editing while processing new data.'),
('msg_ingest_no_identifier_descriptions', 'en', 'The target Type does not contain Object Descriptions that are designated as Object identifier.'),
('msg_ingest_no_webservice_client', 'en', 'This Ingestion Process requires a connection to an additional webservice that is currently not active. Please wait a moment and try again.'),
('msg_ingest_stopped', 'en', 'The ingestion process stopped.'),
('msg_ingest_strings_found', 'en', 'Found <strong>[V][count]</strong> new strings to match with Objects in Type <strong>[V][type]</strong>.'),
('msg_ingest_strings_processed', 'en', 'A total of <strong>[V][count_status]</strong> ([V][count_matched] matches / [V][count_new] unidentified) of [V][count] strings in Type <strong>[V][type]</strong> have been processed.'),
('msg_ingest_unmatched_filters', 'en', 'You have over [V][count] unmatched Filters. Please review your Template or [V][source].'),
('msg_ingest_unmatched_results_resolve', 'en', 'Resolve all unmatched results, then continue.'),
('msg_malformed_chronojson', 'en', 'The provided data contains ChronoJSON that is incomplete or contains errors.	'),
('msg_malformed_geometry', 'en', 'The provided data contains [V][type] that is incomplete or contains errors.'),
('msg_malformed_geometry_bounds', 'en', 'The provided data contains [V][type] that has longitudinal and/or longitudinal coordinates that are out of bounds.'),
('msg_malformed_geometry_empty', 'en', 'The provided data contains [V][type] that is empty.'),
('msg_malformed_xml', 'en', 'The provided data cannot be formatted to valid XML.'),
('msg_model_no_object_name', 'en', 'The Data Model does not have a configuration that can be used to generate Object names, please check your settings.'),
('msg_model_recursion_in_name', 'en', 'The name for the Object contains recursion, please check your Object Description settings.'),
('msg_model_recursion_in_search', 'en', 'The quick search for the Object contains recursion, please check your Object Description settings.'),
('msg_model_type_share', 'en', 'This [V][type_class] has mode <strong>[V][type_mode]</strong>. This [V][type_class] can be used by all other nodegoat Domains on the system. Only system administrators have privileges to make adjustments to this Data Model.'),
('msg_model_types_not_share', 'en', '<p>The following Types are part of the Data Model for <strong>[V][type_name]</strong> but are currently not in Share mode:</p>\r\n<ul>\r\n[V][types_not_share]\r\n</ul>'),
('msg_model_types_share', 'en', '<p>The following Types are part of the Data Model for <strong>[V][type_name]</strong> and are currently in Share mode:</p>\r\n<ul>[V][types_share]</ul>'),
('msg_no_connections', 'en', 'No connections.'),
('msg_no_custom_project_active', 'en', 'There is currently no Project active in your Domain.'),
('msg_no_custom_project_types', 'en', '<p>There are currently no Types available in this Project.</p>\r\n<p>Go to <strong>Model -> Model</strong> to create your Types and go to <strong>Management -> Projects</strong> to enable these Types in your Project.</p>'),
('msg_no_custom_projects', 'en', '<p>There are currently no Projects available in your Domain.</p>\r\n<p>Go to <strong>Management -> Projects</strong> to create a new Project.</p>'),
('msg_no_discussion', 'en', 'This Object does not have an active Discussion yet.'),
('msg_no_types_domain', 'en', '<p>There are currently no Types available in this Domain.</p>\r\n<p>Go to <strong>Model -> Model</strong> to create your Types.</p>'),
('msg_object_added', 'en', 'A total of [V][count] Objects have been added.'),
('msg_object_definition_is_required', 'en', 'A Definition for [V][field] is required but is missing.'),
('msg_object_definition_not_unique', 'en', 'The Definition <strong>[V][value]</strong> entered for [V][field] has to be unique.'),
('msg_object_deleted', 'en', 'A total of [V][count] Objects have been deleted.'),
('msg_object_description_value_type_missing', 'en', 'The requested Object Description is not supported.'),
('msg_object_error', 'en', 'An error occurred while processing Object [V][object].'),
('msg_object_lock_success', 'en', 'Acquired <strong>successful lock</strong> on all <strong>[V][total]</strong> Objects.'),
('msg_object_locked', 'en', 'The Object <strong>[V][object]</strong> is currently being edited by <strong>[V][user]</strong>.'),
('msg_object_locked_discussion', 'en', 'The Discussion for Object <strong>[V][object]</strong> is currently being edited by <strong>[V][user]</strong>.'),
('msg_object_locked_discussion_self', 'en', 'You are already editing the Discussion for Object <strong>[V][object]</strong>.'),
('msg_object_locked_multi', 'en', 'A total of <strong>[V][total]</strong> Objects are currently being edited:'),
('msg_object_locked_self', 'en', 'You are already editing the Object <strong>[V][object]</strong>.'),
('msg_object_missing', 'en', 'The Object cannot be found.'),
('msg_object_updated', 'en', 'A total of [V][count] Objects have been updated.'),
('msg_reconcile_done', 'en', 'All results have been processed and <strong>[V][count]</strong> Objects have been updated. Go to the [url=/login/data]Data section of your environment[/url] to inspect these Objects.'),
('msg_reconcile_resolve', 'en', 'Resolve each Object with their found matches, then continue.'),
('msg_scenario_store_empty', 'en', 'The Scenario cannot be stored as there is nothing configured.'),
('msg_scope_store_empty', 'en', 'The Scope cannot be stored as the Scope does not contain any valid information.'),
('msg_type_added', 'en', 'A total of [V][count] Types have been added.'),
('msg_type_deleted', 'en', 'A total of [V][count] Types have been deleted.'),
('msg_type_does_not_exist', 'en', 'A Type is configured that does not exist (anymore).'),
('msg_type_updated', 'en', 'A total of [V][count] Types have been updated.'),
('msg_visualisation_not_set', 'en', 'Sorry, there is no data available to visualise.'),
('ttl_analyse', 'en', 'Analyse'),
('ttl_csrp', 'en', 'CSRP'),
('ttl_custom_projects', 'en', 'Custom Projects'),
('ttl_definitions', 'en', 'Definitions'),
('ttl_import', 'en', 'Import'),
('ttl_public_interfaces', 'en', 'Public Interfaces'),
('ttl_visualise', 'en', 'Visualise');
